import "dotenv/config";
import fs from "fs";
import path from "path";
import { isSupabaseMode, isSqlMode, isDbMode } from "../server/sqlConfig.js";
import { getJsonRow, listJsonRows, upsertJsonRow } from "../server/sqlStore.js";
import type { MappedAsset } from "../server/assetHelpers.js";

export const DEMO_MARKER = "AEMS-DEMO-BHIWADI-2026";
export const MANIFEST_PATH = path.join(process.cwd(), "data", "demo_data_manifest.json");

export const DEMO_ASSETS: MappedAsset[] = [
  // =========================================================================
  // 1. ELECTRICAL ASSETS (Bhiwadi) - All with distinct, unique images
  // =========================================================================
  {
    id: "DEMO-BHW-ELE-001",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Electrical",
    make: "Kirloskar",
    model: "KG-250 Silent",
    serialNumber: "KIR-2024-EL-8801",
    assetCode: "ELE-2026-00001",
    accountAssetCode: "FA-BHW-ELE-001",
    vendorName: "Kirloskar Oil Engines Ltd",
    warrantyStartDate: "2024-01-15",
    warrantyEndDate: "2027-01-14",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Diesel Generator",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1590373977797-4028bc166d3a?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|ELE-2026-00001",
    uniqueCode: "AEMS-DEMO-BHIWADI-001",
    binaryCode: "",
    assetName: "Kirloskar 250kVA Prime Silent DG Set",
    mainCategory: "Electrical Assets",
    subCategory: "Diesel Generator",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-01-10",
    purchaseCost: "1250000",
    invoiceNumber: "INV-KIR-2024-098",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-15",
    nextMaintenanceDate: "2026-07-15",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-ELE-002",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Electrical",
    make: "L&T",
    model: "T-Power 415V 1250A",
    serialNumber: "LT-2023-PCC-4412",
    assetCode: "ELE-2026-00002",
    accountAssetCode: "FA-BHW-ELE-002",
    vendorName: "L&T Electrical & Automation",
    warrantyStartDate: "2023-06-01",
    warrantyEndDate: "2026-05-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Power Control Center",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|ELE-2026-00002",
    uniqueCode: "AEMS-DEMO-BHIWADI-002",
    binaryCode: "",
    assetName: "L&T Main LT Power Distribution Panel",
    mainCategory: "Electrical Assets",
    subCategory: "Electrical Panel",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-05-20",
    purchaseCost: "850000",
    invoiceNumber: "INV-LT-2023-551",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-10",
    nextMaintenanceDate: "2026-08-10",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-ELE-003",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Electrical",
    make: "Servomax",
    model: "HT-SERVO 500kVA",
    serialNumber: "SRV-2023-500K-109",
    assetCode: "ELE-2026-00003",
    accountAssetCode: "FA-BHW-ELE-003",
    vendorName: "Servomax India Pvt Ltd",
    warrantyStartDate: "2023-11-01",
    warrantyEndDate: "2026-10-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Voltage Stabilizer",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1601524909162-be87252be298?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|ELE-2026-00003",
    uniqueCode: "AEMS-DEMO-BHIWADI-003",
    binaryCode: "",
    assetName: "Servomax 500kVA Oil Cooled Servo Stabilizer",
    mainCategory: "Electrical Assets",
    subCategory: "Voltage Stabilizer",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-10-15",
    purchaseCost: "420000",
    invoiceNumber: "INV-SRV-2023-772",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2026-07-20",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-ELE-004",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Electrical",
    make: "Emerson Liebert",
    model: "Hipulse-U 120kVA",
    serialNumber: "EME-2024-UPS-9031",
    assetCode: "ELE-2026-00004",
    accountAssetCode: "FA-BHW-ELE-004",
    vendorName: "Vertiv Energy Pvt Ltd",
    warrantyStartDate: "2024-03-01",
    warrantyEndDate: "2027-02-28",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Industrial UPS",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|ELE-2026-00004",
    uniqueCode: "AEMS-DEMO-BHIWADI-004",
    binaryCode: "",
    assetName: "Emerson 120kVA Industrial On-Line 3-Phase UPS",
    mainCategory: "Electrical Assets",
    subCategory: "Industrial UPS",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-02-20",
    purchaseCost: "680000",
    invoiceNumber: "INV-VER-2024-114",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-05",
    nextMaintenanceDate: "2026-08-05",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-ELE-005",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Electrical",
    make: "Havells",
    model: "Pro-Illuma 150W Panel",
    serialNumber: "HAV-2024-HB-3310",
    assetCode: "ELE-2026-00005",
    accountAssetCode: "FA-BHW-ELE-005",
    vendorName: "Havells India Ltd",
    warrantyStartDate: "2024-04-10",
    warrantyEndDate: "2027-04-09",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "High Bay Lighting",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|ELE-2026-00005",
    uniqueCode: "AEMS-DEMO-BHIWADI-005",
    binaryCode: "",
    assetName: "Havells Industrial High Bay LED Lighting Control System",
    mainCategory: "Electrical Assets",
    subCategory: "Lighting System",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-04-01",
    purchaseCost: "175000",
    invoiceNumber: "INV-HAV-2024-819",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2026-07-10",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },

  // =========================================================================
  // 2. PRODUCTION ASSETS (Bhiwadi) - All with distinct, unique images
  // =========================================================================
  {
    id: "DEMO-BHW-PRD-001",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Production",
    make: "Toshiba Machine",
    model: "EC350SXIII All-Electric",
    serialNumber: "TOS-2023-IMM-5521",
    assetCode: "PRD-2026-00001",
    accountAssetCode: "FA-BHW-PRD-001",
    vendorName: "Toshiba Machine India Pvt Ltd",
    warrantyStartDate: "2023-04-15",
    warrantyEndDate: "2026-04-14",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Machine",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|PRD-2026-00001",
    uniqueCode: "AEMS-DEMO-BHIWADI-006",
    binaryCode: "",
    assetName: "Toshiba 350-Ton All-Electric Injection Moulding Machine",
    mainCategory: "Production Assets",
    subCategory: "Machine",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-04-01",
    purchaseCost: "4500000",
    invoiceNumber: "INV-TOS-2023-041",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-12",
    nextMaintenanceDate: "2026-08-12",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-PRD-002",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Production",
    make: "Atlas Copco",
    model: "GA-37 VSD+ FF",
    serialNumber: "ATL-2024-CMP-1104",
    assetCode: "PRD-2026-00002",
    accountAssetCode: "FA-BHW-PRD-002",
    vendorName: "Atlas Copco India Ltd",
    warrantyStartDate: "2024-02-01",
    warrantyEndDate: "2027-01-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Compressor",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|PRD-2026-00002",
    uniqueCode: "AEMS-DEMO-BHIWADI-007",
    binaryCode: "",
    assetName: "Atlas Copco 37kW Rotary Screw Air Compressor",
    mainCategory: "Production Assets",
    subCategory: "Compressor",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-01-20",
    purchaseCost: "1650000",
    invoiceNumber: "INV-ATL-2024-772",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-18",
    nextMaintenanceDate: "2026-07-18",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-PRD-003",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Production",
    make: "Branson",
    model: "2000X 20kHz 4.0kW",
    serialNumber: "BRN-2023-USW-9921",
    assetCode: "PRD-2026-00003",
    accountAssetCode: "FA-BHW-PRD-003",
    vendorName: "Emerson Industrial Automation",
    warrantyStartDate: "2023-08-01",
    warrantyEndDate: "2026-07-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Welding Machine",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|PRD-2026-00003",
    uniqueCode: "AEMS-DEMO-BHIWADI-008",
    binaryCode: "",
    assetName: "Branson Precision Ultrasonic Plastic Welder",
    mainCategory: "Production Assets",
    subCategory: "Welding Machine",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-07-15",
    purchaseCost: "1150000",
    invoiceNumber: "INV-BRN-2023-108",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-25",
    nextMaintenanceDate: "2026-07-25",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-PRD-004",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Production",
    make: "Daifuku",
    model: "Modu-Line 20M Auto",
    serialNumber: "DAI-2023-CNV-0081",
    assetCode: "PRD-2026-00004",
    accountAssetCode: "FA-BHW-PRD-004",
    vendorName: "Daifuku India Pvt Ltd",
    warrantyStartDate: "2023-09-01",
    warrantyEndDate: "2026-08-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Conveyor Belt",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|PRD-2026-00004",
    uniqueCode: "AEMS-DEMO-BHIWADI-009",
    binaryCode: "",
    assetName: "Modular Assembly Line Motorized Belt Conveyor 20M",
    mainCategory: "Production Assets",
    subCategory: "Conveyor Belt",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-08-10",
    purchaseCost: "580000",
    invoiceNumber: "INV-DAI-2023-664",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-01",
    nextMaintenanceDate: "2026-08-01",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-PRD-005",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Production",
    make: "Fanuc",
    model: "Robodrill α-D21LiB5",
    serialNumber: "FAN-2024-CNC-7732",
    assetCode: "PRD-2026-00005",
    accountAssetCode: "FA-BHW-PRD-005",
    vendorName: "Fanuc India Pvt Ltd",
    warrantyStartDate: "2024-05-01",
    warrantyEndDate: "2027-04-30",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Drill Machine",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|PRD-2026-00005",
    uniqueCode: "AEMS-DEMO-BHIWADI-010",
    binaryCode: "",
    assetName: "Fanuc High-Speed CNC Drill Machining Center",
    mainCategory: "Production Assets",
    subCategory: "Drill Machine",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-04-18",
    purchaseCost: "3200000",
    invoiceNumber: "INV-FAN-2024-301",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-15",
    nextMaintenanceDate: "2026-08-15",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-PRD-006",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Production",
    make: "Signode",
    model: "Mod-710 Carton Taper",
    serialNumber: "SIG-2024-PKG-1190",
    assetCode: "PRD-2026-00006",
    accountAssetCode: "FA-BHW-PRD-006",
    vendorName: "Signode India Ltd",
    warrantyStartDate: "2024-06-01",
    warrantyEndDate: "2027-05-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Packing Machine",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|PRD-2026-00006",
    uniqueCode: "AEMS-DEMO-BHIWADI-011",
    binaryCode: "",
    assetName: "Signode High-Speed Automatic Carton Sealing Machine",
    mainCategory: "Production Assets",
    subCategory: "Packing Machine",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-05-20",
    purchaseCost: "450000",
    invoiceNumber: "INV-SIG-2024-912",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-30",
    nextMaintenanceDate: "2026-07-30",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },

  // =========================================================================
  // 3. SAFETY ASSETS (Bhiwadi) - All with distinct, unique images
  // =========================================================================
  {
    id: "DEMO-BHW-SAF-001",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Safety & EHS",
    make: "Ceasefire",
    model: "ABC Stored Pressure 6KG",
    serialNumber: "CF-2024-FE-6019",
    assetCode: "SAF-2026-00001",
    accountAssetCode: "FA-BHW-SAF-001",
    vendorName: "Ceasefire Industries Pvt Ltd",
    warrantyStartDate: "2024-01-01",
    warrantyEndDate: "2029-12-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Fire Extinguisher",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SAF-2026-00001",
    uniqueCode: "AEMS-DEMO-BHIWADI-012",
    binaryCode: "",
    assetName: "Ceasefire ABC 6KG Dry Powder Fire Extinguisher",
    mainCategory: "Safety Assets",
    subCategory: "Fire Extinguisher",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-12-20",
    purchaseCost: "4500",
    invoiceNumber: "INV-CF-2023-441",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-05",
    nextMaintenanceDate: "2026-07-05",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SAF-002",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Safety & EHS",
    make: "Ceasefire",
    model: "Carbon Dioxide 4.5KG Wheel",
    serialNumber: "CF-2024-CO2-8812",
    assetCode: "SAF-2026-00002",
    accountAssetCode: "FA-BHW-SAF-002",
    vendorName: "Ceasefire Industries Pvt Ltd",
    warrantyStartDate: "2024-01-01",
    warrantyEndDate: "2029-12-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Fire Extinguisher",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SAF-2026-00002",
    uniqueCode: "AEMS-DEMO-BHIWADI-013",
    binaryCode: "",
    assetName: "Ceasefire 4.5KG CO2 Electrical Fire Extinguisher",
    mainCategory: "Safety Assets",
    subCategory: "Fire Extinguisher",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-12-20",
    purchaseCost: "8200",
    invoiceNumber: "INV-CF-2023-442",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-05",
    nextMaintenanceDate: "2026-07-05",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SAF-003",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Safety & EHS",
    make: "Honeywell Morley",
    model: "ZX4e Addressable Panel",
    serialNumber: "HON-2023-FAS-3301",
    assetCode: "SAF-2026-00003",
    accountAssetCode: "FA-BHW-SAF-003",
    vendorName: "Honeywell Building Technologies",
    warrantyStartDate: "2023-10-01",
    warrantyEndDate: "2026-09-30",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Fire Alarm System",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SAF-2026-00003",
    uniqueCode: "AEMS-DEMO-BHIWADI-014",
    binaryCode: "",
    assetName: "Honeywell 4-Loop Central Fire Alarm Control Panel",
    mainCategory: "Safety Assets",
    subCategory: "Fire Alarm System",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-09-15",
    purchaseCost: "340000",
    invoiceNumber: "INV-HON-2023-889",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-08",
    nextMaintenanceDate: "2026-08-08",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SAF-004",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Safety & EHS",
    make: "Unicare",
    model: "Comb-Safety Station U-800",
    serialNumber: "UNI-2024-EWS-1092",
    assetCode: "SAF-2026-00004",
    accountAssetCode: "FA-BHW-SAF-004",
    vendorName: "Unicare Emergency Equipment Pvt Ltd",
    warrantyStartDate: "2024-02-15",
    warrantyEndDate: "2027-02-14",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "First Aid Box",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SAF-2026-00004",
    uniqueCode: "AEMS-DEMO-BHIWADI-015",
    binaryCode: "",
    assetName: "Unicare Chemical Emergency Shower & Eyewash Station",
    mainCategory: "Safety Assets",
    subCategory: "First Aid Box",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-02-01",
    purchaseCost: "48000",
    invoiceNumber: "INV-UNI-2024-110",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-28",
    nextMaintenanceDate: "2026-07-28",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SAF-005",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Safety & EHS",
    make: "Prolite",
    model: "LED-EXIT-AutoDual",
    serialNumber: "PRO-2024-EXT-5520",
    assetCode: "SAF-2026-00005",
    accountAssetCode: "FA-BHW-SAF-005",
    vendorName: "Prolite Autoglo Ltd",
    warrantyStartDate: "2024-04-01",
    warrantyEndDate: "2027-03-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Emergency Light",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SAF-2026-00005",
    uniqueCode: "AEMS-DEMO-BHIWADI-016",
    binaryCode: "",
    assetName: "Prolite Photoluminescent LED Emergency Exit Route Luminaire",
    mainCategory: "Safety Assets",
    subCategory: "Emergency Light",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-03-25",
    purchaseCost: "35000",
    invoiceNumber: "INV-PRO-2024-709",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-02",
    nextMaintenanceDate: "2026-08-02",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },

  // =========================================================================
  // 4. VEHICLE ASSETS (Bhiwadi) - All with distinct, unique images
  // =========================================================================
  {
    id: "DEMO-BHW-VEH-001",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Logistics",
    make: "Godrej Material Handling",
    model: "GX 300 Electric 3-Ton",
    serialNumber: "GDJ-2023-FL-3301",
    assetCode: "VEH-2026-00001",
    accountAssetCode: "FA-BHW-VEH-001",
    vendorName: "Godrej & Boyce Mfg Co Ltd",
    warrantyStartDate: "2023-05-15",
    warrantyEndDate: "2026-05-14",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Forklift",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1586864387789-628af9feed72?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|VEH-2026-00001",
    uniqueCode: "AEMS-DEMO-BHIWADI-017",
    binaryCode: "",
    assetName: "Godrej 3-Ton Heavy-Duty Electric Forklift",
    mainCategory: "Vehicle Assets",
    subCategory: "Forklift",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-05-01",
    purchaseCost: "1450000",
    invoiceNumber: "INV-GDJ-2023-119",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-22",
    nextMaintenanceDate: "2026-07-22",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-VEH-002",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Logistics",
    make: "Tata Motors",
    model: "Ace Gold BS6 Container",
    serialNumber: "TAT-2024-ACE-9941",
    assetCode: "VEH-2026-00002",
    accountAssetCode: "FA-BHW-VEH-002",
    vendorName: "Tata Commercial Vehicles",
    warrantyStartDate: "2024-02-01",
    warrantyEndDate: "2027-01-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Truck",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|VEH-2026-00002",
    uniqueCode: "AEMS-DEMO-BHIWADI-018",
    binaryCode: "",
    assetName: "Tata Ace Gold BS6 Inter-Plant Logistics Van",
    mainCategory: "Vehicle Assets",
    subCategory: "Truck",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-01-15",
    purchaseCost: "620000",
    invoiceNumber: "INV-TAT-2024-554",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-05",
    nextMaintenanceDate: "2026-08-05",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-VEH-003",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Logistics",
    make: "Maini Materials",
    model: "M-EPT 2000kg Power Pallet",
    serialNumber: "MAI-2023-BPT-1082",
    assetCode: "VEH-2026-00003",
    accountAssetCode: "FA-BHW-VEH-003",
    vendorName: "Maini Materials Movement Pvt Ltd",
    warrantyStartDate: "2023-07-01",
    warrantyEndDate: "2026-06-30",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Battery Vehicle",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|VEH-2026-00003",
    uniqueCode: "AEMS-DEMO-BHIWADI-019",
    binaryCode: "",
    assetName: "Maini 2-Ton Battery Operated Power Pallet Truck",
    mainCategory: "Vehicle Assets",
    subCategory: "Battery Vehicle",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-06-20",
    purchaseCost: "380000",
    invoiceNumber: "INV-MAI-2023-903",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-15",
    nextMaintenanceDate: "2026-07-15",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-VEH-004",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Administration",
    make: "Mahindra",
    model: "Bolero Camper 4x4",
    serialNumber: "MAH-2024-BOL-4481",
    assetCode: "VEH-2026-00004",
    accountAssetCode: "FA-BHW-VEH-004",
    vendorName: "Mahindra & Mahindra Ltd",
    warrantyStartDate: "2024-03-10",
    warrantyEndDate: "2027-03-09",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Company Car",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|VEH-2026-00004",
    uniqueCode: "AEMS-DEMO-BHIWADI-020",
    binaryCode: "",
    assetName: "Mahindra Bolero Utility Plant Vehicle",
    mainCategory: "Vehicle Assets",
    subCategory: "Company Car",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-02-28",
    purchaseCost: "920000",
    invoiceNumber: "INV-MAH-2024-019",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-14",
    nextMaintenanceDate: "2026-08-14",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },

  // =========================================================================
  // 5. FURNITURE ASSETS (Bhiwadi) - All with distinct, unique images
  // =========================================================================
  {
    id: "DEMO-BHW-FUR-001",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Administration",
    make: "Godrej Interio",
    model: "WorkNest Modular 6-Cluster",
    serialNumber: "GDJ-2024-WS-1102",
    assetCode: "FUR-2026-00001",
    accountAssetCode: "FA-BHW-FUR-001",
    vendorName: "Godrej Interio Ltd",
    warrantyStartDate: "2024-01-01",
    warrantyEndDate: "2027-12-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Workstation",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|FUR-2026-00001",
    uniqueCode: "AEMS-DEMO-BHIWADI-021",
    binaryCode: "",
    assetName: "Godrej Interio Modular 6-Person Cluster Workstation",
    mainCategory: "Furniture Assets",
    subCategory: "Workstation",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-12-15",
    purchaseCost: "125000",
    invoiceNumber: "INV-GI-2023-881",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-05",
    nextMaintenanceDate: "2026-07-05",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-FUR-002",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Administration",
    make: "Featherlite",
    model: "Boardroom 10-Seater Solid Oak",
    serialNumber: "FEA-2023-MT-4401",
    assetCode: "FUR-2026-00002",
    accountAssetCode: "FA-BHW-FUR-002",
    vendorName: "Featherlite Furniture",
    warrantyStartDate: "2023-08-01",
    warrantyEndDate: "2026-07-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Meeting Table",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|FUR-2026-00002",
    uniqueCode: "AEMS-DEMO-BHIWADI-022",
    binaryCode: "",
    assetName: "Featherlite 10-Seater Executive Conference Table with Cable Management",
    mainCategory: "Furniture Assets",
    subCategory: "Meeting Table",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-07-20",
    purchaseCost: "95000",
    invoiceNumber: "INV-FEA-2023-331",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2026-07-10",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-FUR-003",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Administration",
    make: "Featherlite",
    model: "Optima High-Back Ergonomic",
    serialNumber: "FEA-2024-CHR-9011",
    assetCode: "FUR-2026-00003",
    accountAssetCode: "FA-BHW-FUR-003",
    vendorName: "Featherlite Furniture",
    warrantyStartDate: "2024-02-01",
    warrantyEndDate: "2027-01-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Chair",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1580481077197-987829288e40?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|FUR-2026-00003",
    uniqueCode: "AEMS-DEMO-BHIWADI-023",
    binaryCode: "",
    assetName: "Featherlite Optima High-Back Mesh Ergonomic Office Chair",
    mainCategory: "Furniture Assets",
    subCategory: "Chair",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-01-15",
    purchaseCost: "14500",
    invoiceNumber: "INV-FEA-2024-118",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-15",
    nextMaintenanceDate: "2026-07-15",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-FUR-004",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Administration",
    make: "Godrej Interio",
    model: "Storwel Plain 4-Shelf",
    serialNumber: "GDJ-2023-ALM-6621",
    assetCode: "FUR-2026-00004",
    accountAssetCode: "FA-BHW-FUR-004",
    vendorName: "Godrej Interio Ltd",
    warrantyStartDate: "2023-06-01",
    warrantyEndDate: "2026-05-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Almirah",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|FUR-2026-00004",
    uniqueCode: "AEMS-DEMO-BHIWADI-024",
    binaryCode: "",
    assetName: "Godrej Heavy-Duty 4-Shelf Steel Storage Almirah",
    mainCategory: "Furniture Assets",
    subCategory: "Almirah",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-05-25",
    purchaseCost: "28000",
    invoiceNumber: "INV-GI-2023-559",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2026-07-20",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-FUR-005",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Administration",
    make: "Voltas",
    model: "FSS 80/120 Stainless",
    serialNumber: "VOL-2024-WC-7719",
    assetCode: "FUR-2026-00005",
    accountAssetCode: "FA-BHW-FUR-005",
    vendorName: "Voltas Commercial Appliances",
    warrantyStartDate: "2024-03-01",
    warrantyEndDate: "2027-02-28",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Water Dispenser",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|FUR-2026-00005",
    uniqueCode: "AEMS-DEMO-BHIWADI-025",
    binaryCode: "",
    assetName: "Voltas Commercial 80-Liter Stainless Steel Water Cooler",
    mainCategory: "Furniture Assets",
    subCategory: "Water Dispenser",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-02-15",
    purchaseCost: "46000",
    invoiceNumber: "INV-VOL-2024-220",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-01",
    nextMaintenanceDate: "2026-08-01",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },

  // =========================================================================
  // 6. MAINTENANCE ASSETS (Bhiwadi) - All with distinct, unique images
  // =========================================================================
  {
    id: "DEMO-BHW-MNT-001",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Maintenance",
    make: "Fluke",
    model: "Fluke 179 True-RMS",
    serialNumber: "FLK-2024-MM-8831",
    assetCode: "MNT-2026-00001",
    accountAssetCode: "FA-BHW-MNT-001",
    vendorName: "Fluke India Instruments",
    warrantyStartDate: "2024-01-15",
    warrantyEndDate: "2027-01-14",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Multimeter",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|MNT-2026-00001",
    uniqueCode: "AEMS-DEMO-BHIWADI-026",
    binaryCode: "",
    assetName: "Fluke 179 True-RMS Industrial Digital Multimeter",
    mainCategory: "Maintenance Assets",
    subCategory: "Multimeter",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-01-05",
    purchaseCost: "32000",
    invoiceNumber: "INV-FLK-2024-091",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2026-07-10",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-MNT-002",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Maintenance",
    make: "Fluke",
    model: "Fluke 376 FC True-RMS",
    serialNumber: "FLK-2024-CLM-4419",
    assetCode: "MNT-2026-00002",
    accountAssetCode: "FA-BHW-MNT-002",
    vendorName: "Fluke India Instruments",
    warrantyStartDate: "2024-02-01",
    warrantyEndDate: "2027-01-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Clamp Meter",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|MNT-2026-00002",
    uniqueCode: "AEMS-DEMO-BHIWADI-027",
    binaryCode: "",
    assetName: "Fluke 376 FC Wireless AC/DC Clamp Meter with iFlex",
    mainCategory: "Maintenance Assets",
    subCategory: "Clamp Meter",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-01-20",
    purchaseCost: "48000",
    invoiceNumber: "INV-FLK-2024-118",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2026-07-10",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-MNT-003",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Maintenance",
    make: "Enerpac",
    model: "P-392 700-Bar Two-Speed",
    serialNumber: "ENR-2023-HYD-5501",
    assetCode: "MNT-2026-00003",
    accountAssetCode: "FA-BHW-MNT-003",
    vendorName: "Enerpac Hydraulics India",
    warrantyStartDate: "2023-09-01",
    warrantyEndDate: "2026-08-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Tool Box",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|MNT-2026-00003",
    uniqueCode: "AEMS-DEMO-BHIWADI-028",
    binaryCode: "",
    assetName: "Enerpac 700-Bar Hydraulic Two-Speed Hand Pump Kit",
    mainCategory: "Maintenance Assets",
    subCategory: "Tool Box",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2023-08-15",
    purchaseCost: "78000",
    invoiceNumber: "INV-ENR-2023-881",
    condition: "Good",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2026-07-20",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-MNT-004",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Maintenance",
    make: "Groz",
    model: "BOP-50 Heavy Duty Air",
    serialNumber: "GRZ-2024-GG-9921",
    assetCode: "MNT-2026-00004",
    accountAssetCode: "FA-BHW-MNT-004",
    vendorName: "Groz Engineering Tools Pvt Ltd",
    warrantyStartDate: "2024-03-01",
    warrantyEndDate: "2027-02-28",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Grease Gun",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|MNT-2026-00004",
    uniqueCode: "AEMS-DEMO-BHIWADI-029",
    binaryCode: "",
    assetName: "Groz 50:1 Air Operated Industrial Grease Dispensing System",
    mainCategory: "Maintenance Assets",
    subCategory: "Grease Gun",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-02-10",
    purchaseCost: "26000",
    invoiceNumber: "INV-GRZ-2024-340",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-25",
    nextMaintenanceDate: "2026-07-25",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-MNT-005",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Maintenance",
    make: "Youngman",
    model: "Fibreglass Step 12ft",
    serialNumber: "YNG-2024-LAD-1102",
    assetCode: "MNT-2026-00005",
    accountAssetCode: "FA-BHW-MNT-005",
    vendorName: "Youngman India Pvt Ltd",
    warrantyStartDate: "2024-04-01",
    warrantyEndDate: "2027-03-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Ladder",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|MNT-2026-00005",
    uniqueCode: "AEMS-DEMO-BHIWADI-030",
    binaryCode: "",
    assetName: "Youngman 12-Foot Heavy-Duty Non-Conductive Fibreglass Platform Ladder",
    mainCategory: "Maintenance Assets",
    subCategory: "Ladder",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-03-15",
    purchaseCost: "38000",
    invoiceNumber: "INV-YNG-2024-512",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-30",
    nextMaintenanceDate: "2026-07-30",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  // =========================================================================
  // 7. SOFTWARE / LICENSE ASSETS (Bhiwadi) - Specific Software Covers
  // =========================================================================
  {
    id: "DEMO-BHW-SW-001",
    location: "BHIWADI",
    plantCode: "4020",
    department: "IT & Systems",
    make: "Microsoft",
    model: "Windows 11 Enterprise (50-Seat Volume)",
    serialNumber: "MS-W11-ENT-8821",
    assetCode: "SW-2026-00001",
    accountAssetCode: "FA-BHW-SW-001",
    vendorName: "Microsoft India Pvt Ltd",
    warrantyStartDate: "2024-01-01",
    warrantyEndDate: "2029-12-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "Windows 11 Enterprise",
    assetType: "Windows License",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SW-2026-00001",
    uniqueCode: "AEMS-DEMO-BHIWADI-031",
    binaryCode: "",
    assetName: "Microsoft Windows 11 Enterprise Volume License (50 Seats)",
    mainCategory: "Software / License Assets",
    subCategory: "Windows License",
    quantity: "50",
    employeeId: "",
    purchaseDate: "2024-01-10",
    purchaseCost: "280000",
    invoiceNumber: "INV-MS-2024-011",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-15",
    nextMaintenanceDate: "2026-07-15",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SW-002",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Administration",
    make: "Microsoft",
    model: "Microsoft 365 Business Premium",
    serialNumber: "M365-BP-2024-441",
    assetCode: "SW-2026-00002",
    accountAssetCode: "FA-BHW-SW-002",
    vendorName: "Microsoft India Pvt Ltd",
    warrantyStartDate: "2024-02-01",
    warrantyEndDate: "2027-01-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "MS Office License",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SW-2026-00002",
    uniqueCode: "AEMS-DEMO-BHIWADI-032",
    binaryCode: "",
    assetName: "Microsoft 365 Business Premium Enterprise Cloud Suite",
    mainCategory: "Software / License Assets",
    subCategory: "MS Office License",
    quantity: "25",
    employeeId: "",
    purchaseDate: "2024-01-25",
    purchaseCost: "195000",
    invoiceNumber: "INV-MS-2024-884",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-01",
    nextMaintenanceDate: "2026-08-01",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SW-003",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Production",
    make: "Autodesk",
    model: "AutoCAD 2024 Plant Design & Engineering Suite",
    serialNumber: "ACAD-2024-ENG-901",
    assetCode: "SW-2026-00003",
    accountAssetCode: "FA-BHW-SW-003",
    vendorName: "Autodesk India Pvt Ltd",
    warrantyStartDate: "2024-03-01",
    warrantyEndDate: "2027-02-28",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "AutoCAD License",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1581291518655-9523c93269c3?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SW-2026-00003",
    uniqueCode: "AEMS-DEMO-BHIWADI-033",
    binaryCode: "",
    assetName: "Autodesk AutoCAD 2024 Engineering Design Commercial License",
    mainCategory: "Software / License Assets",
    subCategory: "AutoCAD License",
    quantity: "5",
    employeeId: "",
    purchaseDate: "2024-02-15",
    purchaseCost: "340000",
    invoiceNumber: "INV-ADSK-2024-109",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2026-07-20",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SW-004",
    location: "BHIWADI",
    plantCode: "4020",
    department: "Finance & Accounts",
    make: "SAP",
    model: "SAP S/4HANA Enterprise Cloud",
    serialNumber: "SAP-S4H-2024-551",
    assetCode: "SW-2026-00004",
    accountAssetCode: "FA-BHW-SW-004",
    vendorName: "SAP India Pvt Ltd",
    warrantyStartDate: "2024-01-01",
    warrantyEndDate: "2027-12-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "ERP License",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SW-2026-00004",
    uniqueCode: "AEMS-DEMO-BHIWADI-034",
    binaryCode: "",
    assetName: "SAP S/4HANA Enterprise Resource Planning User License",
    mainCategory: "Software / License Assets",
    subCategory: "ERP License",
    quantity: "15",
    employeeId: "",
    purchaseDate: "2024-01-05",
    purchaseCost: "850000",
    invoiceNumber: "INV-SAP-2024-331",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2026-07-10",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SW-005",
    location: "BHIWADI",
    plantCode: "2040",
    department: "Finance & Accounts",
    make: "Tally Solutions",
    model: "TallyPrime Gold Multi-User Server",
    serialNumber: "TAL-PRIME-2024-77",
    assetCode: "SW-2026-00005",
    accountAssetCode: "FA-BHW-SW-005",
    vendorName: "Tally Solutions Pvt Ltd",
    warrantyStartDate: "2024-04-01",
    warrantyEndDate: "2027-03-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Tally License",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SW-2026-00005",
    uniqueCode: "AEMS-DEMO-BHIWADI-035",
    binaryCode: "",
    assetName: "TallyPrime Gold Multi-User GST Accounting & Inventory License",
    mainCategory: "Software / License Assets",
    subCategory: "Tally License",
    quantity: "1",
    employeeId: "",
    purchaseDate: "2024-03-20",
    purchaseCost: "54000",
    invoiceNumber: "INV-TAL-2024-512",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-02-01",
    nextMaintenanceDate: "2026-08-01",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
  {
    id: "DEMO-BHW-SW-006",
    location: "BHIWADI",
    plantCode: "4020",
    department: "IT & Systems",
    make: "CrowdStrike",
    model: "Falcon Enterprise EDR (50 Endpoints)",
    serialNumber: "CS-FALCON-2024-99",
    assetCode: "SW-2026-00006",
    accountAssetCode: "FA-BHW-SW-006",
    vendorName: "CrowdStrike Inc",
    warrantyStartDate: "2024-01-01",
    warrantyEndDate: "2027-12-31",
    ram: "", ssd: "", cpu: "", windowsVersion: "",
    assetType: "Antivirus License",
    ipAddress: "", hostName: "", macAddress: "",
    monitorSerial: "", monitorAssetCode: "", monitorMake: "", monitorModel: "",
    keyboardSerial: "", keyboardAssetCode: "", keyboardMake: "", keyboardModel: "", keyboardConnectivity: "",
    mouseSerial: "", mouseAssetCode: "", mouseMake: "", mouseModel: "", mouseConnectivity: "",
    upsSerial: "", upsAssetCode: "", upsMake: "", upsModel: "",
    contactName: "", contactEmail: "", contactMobile: "",
    documentUrl: "",
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=900&q=85",
    additionalItems: "",
    qrCodeText: "AEMS-DEMO-BHIWADI-2026|SW-2026-00006",
    uniqueCode: "AEMS-DEMO-BHIWADI-036",
    binaryCode: "",
    assetName: "CrowdStrike Falcon Enterprise Endpoint Protection & EDR",
    mainCategory: "Software / License Assets",
    subCategory: "Antivirus License",
    quantity: "50",
    employeeId: "",
    purchaseDate: "2024-01-15",
    purchaseCost: "120000",
    invoiceNumber: "INV-CS-2024-904",
    condition: "Excellent",
    status: "Available",
    maintenanceRequired: "No",
    lastMaintenanceDate: "2026-01-15",
    nextMaintenanceDate: "2026-07-15",
    createdBy: DEMO_MARKER,
    createdDate: "2026-02-01",
  },
];

async function run() {
  console.log("=== AEMS SAFE DEMO DATA POPULATION & IMAGE SYNC ===");
  console.log(`Demo Marker: ${DEMO_MARKER}`);
  console.log(`Target Location: BHIWADI ONLY`);
  console.log(`Target Count: ${DEMO_ASSETS.length} records`);

  // Verify before state
  const existingAssets = await listJsonRows<MappedAsset>("Assets");
  console.log(`Pre-check: Total existing assets in DB = ${existingAssets.length}`);

  // Safety assertions on existing real IT Hardware assets
  const realItHardwareCount = existingAssets.filter(
    (a) => a.mainCategory === "IT Assets" && a.createdBy !== DEMO_MARKER
  ).length;
  console.log(`Pre-check: Real IT Hardware Assets = ${realItHardwareCount} (Will remain 100% UNTOUCHED)`);

  let updatedCount = 0;
  const manifestRecords: Array<{
    id: string;
    uniqueCode: string;
    assetCode: string;
    assetName: string;
    category: string;
    location: string;
    plantCode: string;
    marker: string;
  }> = [];

  for (const demoAsset of DEMO_ASSETS) {
    // 1. Mandatory Location constraint check
    if (demoAsset.location !== "BHIWADI") {
      throw new Error(`CRITICAL ABORT: Attempted to insert non-Bhiwadi record: ${demoAsset.id}`);
    }

    // 2. Mandatory Zero-Touch checks
    if (
      demoAsset.mainCategory === "IT Assets" ||
      demoAsset.employeeId ||
      demoAsset.createdBy !== DEMO_MARKER
    ) {
      throw new Error(`CRITICAL ABORT: Zero-touch rule violated on record: ${demoAsset.id}`);
    }

    await upsertJsonRow("Assets", demoAsset.id, demoAsset, {
      AssetCode: demoAsset.assetCode,
      SerialNumber: demoAsset.serialNumber,
      MainCategory: demoAsset.mainCategory,
      Location: demoAsset.location,
      PlantCode: demoAsset.plantCode,
      EmployeeId: demoAsset.employeeId,
      Status: demoAsset.status,
    });
    console.log(`[UPSERTED WITH IMAGE] ${demoAsset.id} -> ${demoAsset.assetName}`);
    updatedCount++;

    manifestRecords.push({
      id: demoAsset.id,
      uniqueCode: demoAsset.uniqueCode,
      assetCode: demoAsset.assetCode,
      assetName: demoAsset.assetName,
      category: demoAsset.mainCategory,
      location: demoAsset.location,
      plantCode: demoAsset.plantCode,
      marker: DEMO_MARKER,
    });
  }

  // Write safe manifest file for complete reversibility
  const manifest = {
    demoMarker: DEMO_MARKER,
    generatedAt: new Date().toISOString(),
    location: "BHIWADI",
    totalRecords: manifestRecords.length,
    updatedCount,
    records: manifestRecords,
  };

  fs.mkdirSync(path.dirname(MANIFEST_PATH), { recursive: true });
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2), "utf-8");
  console.log(`\nManifest written to: ${MANIFEST_PATH}`);

  // Verify post state
  const postAssets = await listJsonRows<MappedAsset>("Assets");
  console.log(`\nPost-check: Total assets in DB = ${postAssets.length}`);
  const postItHardwareCount = postAssets.filter(
    (a) => a.mainCategory === "IT Assets" && a.createdBy !== DEMO_MARKER
  ).length;
  console.log(`Post-check: Real IT Hardware Assets = ${postItHardwareCount} (Verified EQUAL: ${realItHardwareCount === postItHardwareCount})`);

  console.log("\nCategory breakdown in DB:");
  const catBreakdown: Record<string, number> = {};
  postAssets.forEach((a) => {
    const cat = a.mainCategory || a.assetType || "Uncategorized";
    catBreakdown[cat] = (catBreakdown[cat] || 0) + 1;
  });
  console.table(catBreakdown);

  console.log("\n=== DEMO DATA IMAGE SYNC COMPLETED SUCCESSFULLY ===");
}

run().catch((err) => {
  console.error("FATAL ERROR during demo data population:", err);
  process.exit(1);
});
