/** Must match gas/WebApp.gs CATEGORY_HEADERS + IT_EXTRA_HEADERS */
export const CATEGORY_HEADERS = [
  "Asset ID",
  "Asset Code",
  "Account Asset Code",
  "Asset Name",
  "Main Category",
  "Sub Category",
  "Asset Type",
  "Brand",
  "Model",
  "Serial Number",
  "Quantity",
  "Plant Name",
  "Location",
  "Department",
  "Assigned To",
  "Employee ID",
  "Assigned Date",
  "Purchase Date",
  "Purchase Cost",
  "Vendor Name",
  "Invoice Number",
  "Warranty Start Date",
  "Warranty Expiry Date",
  "Condition",
  "Status",
  "Maintenance Required",
  "Last Maintenance Date",
  "Next Maintenance Date",
  "AMC Vendor",
  "AMC Start Date",
  "AMC End Date",
  "AMC Cost",
  "Photo URL / Photo Upload",
  "Document URL / Attached Documents",
  "QR Code / Barcode",
  "Remarks",
  "Created By",
  "Created Date",
  "Updated By",
  "Updated Date",
  "Contact Email",
  "Contact Number",
] as const;

export const IT_EXTRA_HEADERS = [
  "RAM",
  "SSD",
  "CPU",
  "Windows Version",
  "MAC Address",
  "IP Address",
  "Host Name",
  "Unique Code",
  "Binary Code",
  "Monitor Serial",
  "Monitor Asset Code",
  "Monitor Brand",
  "Monitor Model Number",
  "Keyboard Serial",
  "Keyboard Asset Code",
  "Keyboard Brand",
  "Keyboard Model Number",
  "Keyboard Connectivity",
  "Mouse Serial",
  "Mouse Asset Code",
  "Mouse Brand",
  "Mouse Model Number",
  "Mouse Connectivity",
  "UPS Serial",
  "UPS Asset Code",
  "UPS Brand",
  "UPS Model Number",
] as const;

export function getDefaultAssetHeaders(): string[] {
  return [...CATEGORY_HEADERS, ...IT_EXTRA_HEADERS];
}
